name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - run: npm ci
      - run: npm test
      - run: npm run build
      
      # Update version without triggering git scripts
      - name: Set version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          npm --no-git-tag-version version $VERSION --allow-same-version
        env:
          npm_config_version: ''
          npm_config_postversion: ''
      
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}